<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWOjLbvS\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWOjLbvS/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWOjLbvS.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWOjLbvS\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWOjLbvS\App_KernelDevDebugContainer([
    'container.build_hash' => 'WOjLbvS',
    'container.build_id' => '1ac449f8',
    'container.build_time' => 1719592829,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWOjLbvS');
